### ISSUE TITLE
Bot started betting phase today

### ISSUE THREAD

**Issue by Freakspot** [DevWars/DW_Bot#1]
On today's Zen game, betting was started by the bot and Steven had to close them manually.
I'm fairly sure you wanted that to be disabled, so you maybe wish to check that out.

**Comment by DonPage** [comment]
@Freakspot - I'll look into this.

**Comment by DonPage** [comment]
Looks like game.theme is not the actual game type; This is what the game object looks like:
```
{
  "@id": "1",
  "id": 851968,
  "meta": null,
  "created_at": 1523493049000,
  "updated_at": 1523493049000,
  "timestamp": 1524934800000,
  "season": 3,
  "active": false,
  "name": "Classic",
  "theme": "Drawing",
}
```
